### ISSUE TITLE
Cannot read property 'object' of undefined

### ISSUE THREAD

**Issue by jayspirits** [sahlhoff/react-native-pulse#12]
The package generates error because of PropTypes. i checked the code and the is its still importing Proptypes inside react and its already been deprecated since v15.5.

**Comment by sahlhoff** [comment]
@jayspirits yes, this has been fixed with #11 I will publish a new build to reflect this on npm. Thank you.

**Comment by jayspirits** [comment]
I pointed on the master branch as of the moment :D
