### ISSUE TITLE
Invariant Violation error on install

### ISSUE THREAD

**Issue by maxbeech** [sahlhoff/react-native-pulse#15]
Hey!

Love the animation - but having a bit of issue adding it. I keep getting the following error whenever I add the `const Pulse = require("react-native-pulse")` line. 

Any help much appreciated!

`Invariant Violation: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object.`

![simulator screen shot - iphone 6 - 2018-08-14 at 18 14 52](https://user-images.githubusercontent.com/8388201/44107000-fa37d1ac-9fed-11e8-9056-c5c60e8f1a70.png)

**Comment by maxbeech** [comment]
Fixed this with .default at end of require statement.

**Comment by aGORyan** [comment]
Suggest documentation update:

const Pulse = require('react-native-pulse').default;

**Comment by maxbeech** [comment]
Great shout @aGORyan - I have submitted a pull request.
