### ISSUE TITLE
Need to clear Intervals on Unmount

### ISSUE THREAD

**Issue by joncursi** [sahlhoff/react-native-pulse#2]
This component creates a few `setInterval`s. They need to be cleared when the component is unmounted. Otherwise, the intervals will continue to run but the component does not exist so the console will throw errors:

```
ExceptionsManager.js:78 Warning: setState(...): Can only update a mounted or mounting component. This usually means you called setState() on an unmounted component. This is a no-op. Please check the code for the Pulse component.
```

**Comment by sahlhoff** [comment]
Thanks again. Just pushed a fix.

**Comment by joncursi** [comment]
👍
