### ISSUE TITLE
Issue: React setState can only update a mounted or mounting component

### ISSUE THREAD

**Issue by levsthings** [sahlhoff/react-native-pulse#6]
@sahlhoff I really like the module but I'm having a problem with the `React setState can only update a mounted or mounting component` warning when changing views thus unmounting a component which uses this module.
 
Do you have any plans for clearing the callbacks?

**Comment by sahlhoff** [comment]
@levsthings no plans currently. Accepting PR's if you want to contribute. If not I'll look at it this over the weekend.

-Chad

**Comment by yerushanuh** [comment]
@sahlhoff I believe I have resolved this issue with my pull request last time: https://github.com/sahlhoff/react-native-pulse/pull/5

But the npm package has not been updated.

**Comment by levsthings** [comment]
Clearing the timers was a great addition but that doesn't fix this particular problem. (I'm using the component from the repo.)

I'll post a detailed issue report in a few hours.

**Comment by levsthings** [comment]
**React Native Version :  0.42.0**
**React-Native-Pulse Version : Latest from the GitHub Repo**

Problem: When user navigates away from a component that is rendering Pulse, you get the following warning. (Even though Pulse is dismounted.) 

_Warning: setState(...): Can only update a mounted or mounting component. This usually means you called setState() on an unmounted component. This is a no-op. Please check the code for the Pulse component._

**StackTrace:** 
```
/project/node_modules/react-native/Libraries/Renderer/src/renderers/shared/stack/reconciler/ReactUpdateQueue.js:48
/project/node_modules/react-native/Libraries/Renderer/src/renderers/shared/stack/reconciler/ReactUpdateQueue.js:234
/project/components/Pulse.js:106
/project/components/Pulse.js:60
/project/node_modules/react-native/Libraries/Core/Timers/JSTimers.js:80
/project/node_modules/react-native/Libraries/Core/Timers/JSTimers.js:80
/project/node_modules/react-native/Libraries/Core/Timers/JSTimersExecution.js:136
/project/node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:108
/project/node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:46
/project/node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:107
```
I'm trying to think of some solutions but couldn't come with anything other than suppressing the warnings with a hacky method. Any ideas @sahlhoff @yerushanuh ?

**Comment by muresanandrei** [comment]
So is there a fix for this?

**Comment by glebcha** [comment]
@muresanandrei @sahlhoff you can watch/merge my PR https://github.com/sahlhoff/react-native-pulse/pull/7

**Comment by sahlhoff** [comment]
Closing this after merging #7
