### ISSUE TITLE
unable to load image url

### ISSUE THREAD

**Issue by raymclee** [sahlhoff/react-native-pulse#9]
Hi there, is this support to load image from url with below code?

`<Pulse
                color="orange"
                numPulses={3}
                diameter={400}
                speed={20}
                duration={2000}
                image={{
                  source: {
                    uri:
                      "http://www.freeiconspng.com/uploads/calendar-date-event-month-icon--19.png"
                  }
                }}
              />`

**Comment by gauravasrivastava** [comment]
I have a similar requirement.  is it supported? If yes, Please share some example.

**Comment by glebcha** [comment]
@gauravasrivastava sure you can. Just look at https://github.com/sahlhoff/react-native-pulse/blob/d55a784bc61f2325cea09b6c34c1696158e20460/pulse.js#L169 and  [follow official RN guide for Image component](https://facebook.github.io/react-native/docs/image.html)

**Comment by Xifeat** [comment]
Same issue, 

did I miss something with image={source={require('../picture/logo.png')}} ?

**Comment by kodie** [comment]
@cheuk3 @Xifeat Try specifying the image's `style` prop with `width` and `height` properties set:

```jsx
<Pulse
  color="orange"
  numPulses={3}
  diameter={400}
  speed={20}
  duration={2000}
  image={{
    source: { uri: "http://www.freeiconspng.com/uploads/calendar-date-event-month-icon--19.png" }
    style: { width: 50, height: 50 }
  }} />
```

**Comment by waris117** [comment]
also image is not centred on pulse, update style for following view  and add {alignItems: 'center', justifyContent: 'center'} to centre image on pulse
<View style={[pulseWrapperStyle, {alignItems: 'center', justifyContent: 'center'}]}>

**Comment by sandipchandra17** [comment]
Can you please provide a sample code how to use image in the center of Pulse.

**Comment by eramudeep** [comment]
> also image is not centred on pulse, update style for following view and add {alignItems: 'center', justifyContent: 'center'} to centre image on pulse
> <View style={[pulseWrapperStyle, {alignItems: 'center', justifyContent: 'center'}]}>

Yo man thanks. :)
